### ISSUE TITLE
struct error: short format requires

### ISSUE THREAD

**Issue by Tovape** [DGIorio/nfsmw_exporter#1]
Hi I've been following along the youtube tutorial and can't get this error out

![image](https://user-images.githubusercontent.com/49490716/232329973-86361203-696f-4b99-983b-cb177af83be8.png)

**Comment by Tovape** [comment]
Fixed it, turns out my objects were scaled 0.025, a simple apply scale fixed it

**Comment by jonathanpeacock1** [comment]
i try importing of ferrari sc40, but it didn't work

**Comment by Tovape** [comment]
> i try importing of ferrari sc40, but it didn't work

join the discord from nfsmods.xyz and show what error you're getting, i suggest you ask people in dms, that server is pure garbage
